[project]
name = "notes"
version = "0.1.0"
description = "Notes web-app"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "fastapi>=0.141.1",
    "python-dotenv>=1.2.3",
    "requests>=2.32.0",
    "sqlalchemy>=2.0.54",
    "streamlit>=1.64.0",
    "supabase>=2.31.0",
    "uvicorn>=0.53.0",
    "pydantic[email]>=2.13.5",
    "psycopg2-binary>=2.9.10",
]